openapi: 3.0.2
info:
  contact:
    email: api@aweber.com
    name: API Team
    url: https://labs.aweber.com
  description: REST API for access the AWeber service.
  title: Landing Pages
  version: "1.0"
servers:
- url: /
tags:
- name: Landing Pages
paths:
  /accounts/{accountId}/lists/{listId}/landing_pages:
    get:
      description: This endpoint is used to get a paginated collection of list landing
        pages.
      parameters:
      - description: The account ID
        in: path
        name: accountId
        required: true
        schema:
          format: int32
          type: integer
      - description: The list ID
        in: path
        name: listId
        required: true
        schema:
          format: int32
          type: integer
      - description: The pagination starting offset
        in: query
        name: ws.start
        schema:
          default: 0
          format: int32
          minimum: 0
          type: integer
      - description: The pagination total entries to retrieve
        in: query
        name: ws.size
        schema:
          default: 100
          format: int32
          maximum: 100
          minimum: 1
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LandingPages'
          description: The request completed successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_400_response'
          description: The server cannot or will not process the request due to a
            client error
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_401_response'
          description: The request could not be completed due to an authentication
            error
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_403_response'
          description: The request could not be completed due to a rate limit error
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_404_response'
          description: The requested resource could not be found
        "410":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_410_response'
          description: The request has been blocked
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_500_response'
          description: The request failed due to an internal error in the code or
            because of an external dependency failure
        "503":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_503_response'
          description: The server is currently unavailable
      security:
      - OAuth 2.0:
        - landing-page.read
      summary: Get landing pages
      tags:
      - Landing Pages
      x-code-samples:
        $ref: _code_samples.yaml#/code_samples/GetLandingPages
  /accounts/{accountId}/lists/{listId}/landing_pages/{landingPageId}:
    get:
      description: |
        This endpoint is used to retrieve the information for the specified landing page.
      parameters:
      - description: The account ID
        in: path
        name: accountId
        required: true
        schema:
          format: int32
          type: integer
      - description: The list ID
        in: path
        name: listId
        required: true
        schema:
          format: int32
          type: integer
      - description: The landing page ID
        in: path
        name: landingPageId
        required: true
        schema:
          format: uuid
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LandingPage'
          description: The request completed successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages__landingPageId__get_400_response'
          description: The server cannot or will not process the request due to a
            client error
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_401_response'
          description: The request could not be completed due to an authentication
            error
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_403_response'
          description: The request could not be completed due to a rate limit error
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_404_response'
          description: The requested resource could not be found
        "410":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_410_response'
          description: The request has been blocked
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_500_response'
          description: The request failed due to an internal error in the code or
            because of an external dependency failure
        "503":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_503_response'
          description: The server is currently unavailable
      security:
      - OAuth 2.0:
        - list.read
      summary: Get landing page
      tags:
      - Landing Pages
      x-code-samples:
        $ref: _code_samples.yaml#/code_samples/GetLandingPage
components:
  parameters:
    accountId:
      description: The account ID
      in: path
      name: accountId
      required: true
      schema:
        format: int32
        type: integer
    listId:
      description: The list ID
      in: path
      name: listId
      required: true
      schema:
        format: int32
        type: integer
    wsStart:
      description: The pagination starting offset
      in: query
      name: ws.start
      schema:
        default: 0
        format: int32
        minimum: 0
        type: integer
    wsSize:
      description: The pagination total entries to retrieve
      in: query
      name: ws.size
      schema:
        default: 100
        format: int32
        maximum: 100
        minimum: 1
        type: integer
    landingPageId:
      description: The landing page ID
      in: path
      name: landingPageId
      required: true
      schema:
        format: uuid
        type: string
  responses:
    UnauthorizedError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_401_response'
      description: The request could not be completed due to an authentication error
    ForbiddenError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_403_response'
      description: The request could not be completed due to a rate limit error
    NotFound:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_404_response'
      description: The requested resource could not be found
    BlockedError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_410_response'
      description: The request has been blocked
    InternalServerError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_500_response'
      description: The request failed due to an internal error in the code or because
        of an external dependency failure
    ServiceUnavailable:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_503_response'
      description: The server is currently unavailable
    BadOAuth1:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages__landingPageId__get_400_response'
      description: The server cannot or will not process the request due to a client
        error
  schemas:
    LandingPages:
      example:
        entries:
        - resource_type_link: https://api.aweber.com/1.0/#landing_page
          name: My Awesome Landing Page
          created_at: 2000-01-23T04:56:07.000+00:00
          id: 48b38cd9-a5df-4297-8987-ed31b3093b39
          modified_at: 2000-01-23T04:56:07.000+00:00
          published_at: 2000-01-23T04:56:07.000+00:00
          self_link: https://api.aweber.com/1.0/accounts/123/lists/456/landing_pages/48b38cd9-a5df-4297-8987-ed31b3093b39
          published_url: https://awd415f.aweberpages.com/awesomepage
          status: published
        - resource_type_link: https://api.aweber.com/1.0/#landing_page
          name: My Awesome Landing Page
          created_at: 2000-01-23T04:56:07.000+00:00
          id: 48b38cd9-a5df-4297-8987-ed31b3093b39
          modified_at: 2000-01-23T04:56:07.000+00:00
          published_at: 2000-01-23T04:56:07.000+00:00
          self_link: https://api.aweber.com/1.0/accounts/123/lists/456/landing_pages/48b38cd9-a5df-4297-8987-ed31b3093b39
          published_url: https://awd415f.aweberpages.com/awesomepage
          status: published
        prev_collection_link: https://api.aweber.com/1.0/accounts/123/lists/456/landing_pages/48b38cd9-a5df-4297-8987-ed31b3093b39?ws.start=0
        resource_type_link: https://api.aweber.com/1.0/#landing_page-page-resource
        start: 0
        total_size: 100
        next_collection_link: https://api.aweber.com/1.0/accounts/123/lists/456/landing_pages/48b38cd9-a5df-4297-8987-ed31b3093b39?ws.start=10&ws.size=10
      properties:
        entries:
          items:
            $ref: '#/components/schemas/LandingPageNoContent'
          type: array
        next_collection_link:
          description: A link to the next page of entries if more entries exist. This
            attribute is omitted from the collection if there are no more entries.
          example: https://api.aweber.com/1.0/accounts/123/lists/456/landing_pages/48b38cd9-a5df-4297-8987-ed31b3093b39?ws.start=10&ws.size=10
          format: uri
          type: string
        prev_collection_link:
          description: A link to the previous page of entries if any exist. This attribute
            is omitted from the collection if ws.start is 0.
          example: https://api.aweber.com/1.0/accounts/123/lists/456/landing_pages/48b38cd9-a5df-4297-8987-ed31b3093b39?ws.start=0
          format: uri
          type: string
        resource_type_link:
          description: The link to the landing page page type
          example: https://api.aweber.com/1.0/#landing_page-page-resource
          format: uri
          type: string
        start:
          description: The starting offset for the page of entries to retrieve
          minimum: 0
          type: integer
        total_size:
          description: The total number of entries
          example: 100
          minimum: 0
          type: integer
      type: object
    LandingPageNoContent:
      example:
        resource_type_link: https://api.aweber.com/1.0/#landing_page
        name: My Awesome Landing Page
        created_at: 2000-01-23T04:56:07.000+00:00
        id: 48b38cd9-a5df-4297-8987-ed31b3093b39
        modified_at: 2000-01-23T04:56:07.000+00:00
        published_at: 2000-01-23T04:56:07.000+00:00
        self_link: https://api.aweber.com/1.0/accounts/123/lists/456/landing_pages/48b38cd9-a5df-4297-8987-ed31b3093b39
        published_url: https://awd415f.aweberpages.com/awesomepage
        status: published
      properties:
        created_at:
          description: When the landing page was created
          format: date-time
          type: string
        id:
          description: The unique ID for the landing page
          example: 48b38cd9-a5df-4297-8987-ed31b3093b39
          format: uuid
          type: string
        modified_at:
          description: When the landing page was last modified
          format: date-time
          type: string
        name:
          description: The landing page name
          example: My Awesome Landing Page
          type: string
        published_at:
          description: When the landing page was published
          format: date-time
          nullable: true
          type: string
        published_url:
          description: The URL for the landing page
          example: https://awd415f.aweberpages.com/awesomepage
          format: uri
          nullable: true
          type: string
        resource_type_link:
          description: The link to the landing page type
          example: https://api.aweber.com/1.0/#landing_page
          format: uri
          type: string
        self_link:
          description: The link to this resource
          example: https://api.aweber.com/1.0/accounts/123/lists/456/landing_pages/48b38cd9-a5df-4297-8987-ed31b3093b39
          format: uri
          type: string
        status:
          description: The status of the landing page
          enum:
          - published
          - unpublished
          type: string
      type: object
    Endpoint Error:
      example:
        error:
          documentation_url: https://api.aweber.com#unauthorized
          message: Consumer key is invalid.
          type: UnauthorizedError
          status: 6
      properties:
        error:
          $ref: '#/components/schemas/Endpoint_Error_error'
      title: Endpoint Error
      type: object
    Auth Error:
      properties:
        error:
          description: |
            The type of authentication error returned.
            The following error may be received:

            | Error Type       | Explanation                              |
            |------------------|------------------------------------------|
            | invalid_token    | The access token is invalid or has expired |
          example: invalid_token
          type: string
        error_description:
          description: |
            A human friendly description of the error
          example: The access token is invalid or has expired
          type: string
      title: Auth Error
      type: object
    LandingPage:
      allOf:
      - properties:
          content_html:
            description: The draft HTML of the landing page
            example: <html><h1>Title</h1><body>Landing Page Text</body></html>
            type: string
          published_html:
            description: The published HTML of the landing page
            example: <html><h1>Title</h1><body>Landing Page Text</body></html>
            nullable: true
            type: string
        type: object
      - $ref: '#/components/schemas/LandingPageNoContent'
      example:
        resource_type_link: https://api.aweber.com/1.0/#landing_page
        published_html: <html><h1>Title</h1><body>Landing Page Text</body></html>
        name: My Awesome Landing Page
        created_at: 2000-01-23T04:56:07.000+00:00
        id: 48b38cd9-a5df-4297-8987-ed31b3093b39
        modified_at: 2000-01-23T04:56:07.000+00:00
        published_at: 2000-01-23T04:56:07.000+00:00
        self_link: https://api.aweber.com/1.0/accounts/123/lists/456/landing_pages/48b38cd9-a5df-4297-8987-ed31b3093b39
        published_url: https://awd415f.aweberpages.com/awesomepage
        content_html: <html><h1>Title</h1><body>Landing Page Text</body></html>
        status: published
    _accounts__accountId__lists__listId__landing_pages_get_400_response_error:
      description: |
        An error object.
        One of the following errors may be received:

        | Error Type           | Explanation                              |
        |----------------------|------------------------------------------|
        | WebServiceError      | `ws.start` or `ws.size` values are invalid |
        | MissingOAuthParametersError | An OAuth parameter is missing in the request |
        | UnsupportedOAuthVersionError | Unsupported OAuth 1 version |
        | UnsupportedOAuthSignatureMethodError | Unsupported OAuth 1 signature method |

        Please see the message body for more details.
      example:
        documentation_url: https://api.aweber.com#badrequest
        message: Maximum for "ws.size" parameter is 100.
        type: WebServiceError
        status: 400
      properties:
        documentation_url:
          description: A link to the documentation that describes the error
          example: https://api.aweber.com#badrequest
          type: string
        message:
          description: A human friendly description of the error
          example: Maximum for "ws.size" parameter is 100.
          type: string
        status:
          description: The HTTP status code
          example: 400
          type: integer
        type:
          description: The API error type
          example: WebServiceError
          type: string
      type: object
    _accounts__accountId__lists__listId__landing_pages_get_400_response:
      example:
        error:
          documentation_url: https://api.aweber.com#badrequest
          message: Maximum for "ws.size" parameter is 100.
          type: WebServiceError
          status: 400
      properties:
        error:
          $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_400_response_error'
      type: object
    _accounts__accountId__lists__listId__landing_pages_get_401_response:
      oneOf:
      - $ref: '#/components/schemas/Endpoint Error'
      - $ref: '#/components/schemas/Auth Error'
    _accounts__accountId__lists__listId__landing_pages_get_403_response_error:
      description: |
        An error object.
        The following error may be received:

        | Error Type           | Explanation                              |
        |----------------------|------------------------------------------|
        | ForbiddenError       | Rate limit may be reached or account may be suspended |

        Please see the message body for more details.
      example:
        documentation_url: https://api.aweber.com#forbidden
        message: Rate Limit Error
        type: ForbiddenError
        status: 1
      properties:
        documentation_url:
          description: A link to the documentation that describes the error
          example: https://api.aweber.com#forbidden
          type: string
        message:
          description: A human friendly description of the error
          example: Rate Limit Error
          type: string
        status:
          description: The HTTP status code
          enum:
          - 403
          type: integer
        type:
          description: The API error type
          enum:
          - ForbiddenError
          type: string
      type: object
    _accounts__accountId__lists__listId__landing_pages_get_403_response:
      example:
        error:
          documentation_url: https://api.aweber.com#forbidden
          message: Rate Limit Error
          type: ForbiddenError
          status: 1
      properties:
        error:
          $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_403_response_error'
      type: object
    _accounts__accountId__lists__listId__landing_pages_get_404_response_error:
      description: |
        An error object.
        The following error may be received:

        | Error Type           | Explanation                              |
        |----------------------|------------------------------------------|
        | NotFoundError        | The requested resource could not be found |

        Please see the message body for more details.
      example:
        documentation_url: https://api.aweber.com#notfound
        message: "Object: None, name: ''"
        type: NotFoundError
        status: 5
      properties:
        documentation_url:
          description: A link to the documentation that describes the error
          example: https://api.aweber.com#notfound
          type: string
        message:
          description: A human friendly description of the error
          example: "Object: None, name: ''"
          type: string
        status:
          description: The HTTP status code
          enum:
          - 404
          type: integer
        type:
          description: The API error type
          enum:
          - NotFoundError
          type: string
      type: object
    _accounts__accountId__lists__listId__landing_pages_get_404_response:
      example:
        error:
          documentation_url: https://api.aweber.com#notfound
          message: "Object: None, name: ''"
          type: NotFoundError
          status: 5
      properties:
        error:
          $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_404_response_error'
      type: object
    _accounts__accountId__lists__listId__landing_pages_get_410_response_error:
      description: |
        An error object.
        The following error may be received:

        | Error Type           | Explanation                              |
        |----------------------|------------------------------------------|
        | BlockedError         | This Request has been blocked            |

        Please see the message body for more details.
      example:
        documentation_url: https://api.aweber.com/#blocked
        message: Blocked Error
        type: BlockedError
        status: 5
      properties:
        documentation_url:
          description: A link to the documentation that describes the error
          example: https://api.aweber.com/#blocked
          type: string
        message:
          description: A human friendly description of the error
          example: Blocked Error
          type: string
        status:
          description: The HTTP status code
          enum:
          - 410
          type: integer
        type:
          description: The API error type
          enum:
          - BlockedError
          type: string
      type: object
    _accounts__accountId__lists__listId__landing_pages_get_410_response:
      example:
        error:
          documentation_url: https://api.aweber.com/#blocked
          message: Blocked Error
          type: BlockedError
          status: 5
      properties:
        error:
          $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_410_response_error'
      type: object
    _accounts__accountId__lists__listId__landing_pages_get_500_response_error:
      description: |
        An error object.
        The following error may be received:

        | Error Type           | Explanation                              |
        |----------------------|------------------------------------------|
        | InternalServerError    | The request failed due to an internal error |

        Please see the message body for more details.
      example:
        documentation_url: https://api.aweber.com#internalerror
        message: Something went wrong.
        type: InternalServerError
        status: 2
      properties:
        documentation_url:
          description: A link to the documentation that describes the error
          example: https://api.aweber.com#internalerror
          type: string
        message:
          description: A human friendly description of the error
          example: Something went wrong.
          type: string
        status:
          description: The HTTP status code
          enum:
          - 500
          type: integer
        type:
          description: The API error type
          enum:
          - InternalServerError
          type: string
      type: object
    _accounts__accountId__lists__listId__landing_pages_get_500_response:
      example:
        error:
          documentation_url: https://api.aweber.com#internalerror
          message: Something went wrong.
          type: InternalServerError
          status: 2
      properties:
        error:
          $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_500_response_error'
      type: object
    _accounts__accountId__lists__listId__landing_pages_get_503_response_error:
      description: |
        An error object.
        The following error may be received:

        | Error Type           | Explanation                              |
        |----------------------|------------------------------------------|
        | ServiceUnavailableError | The server is unavailable |

        Please see the message body for more details.
      example:
        documentation_url: https://api.aweber.com#serviceunavailable
        message: Failed to communicate with endpoint
        type: ServiceUnavailableError
        status: 7
      properties:
        documentation_url:
          description: A link to the documentation that describes the error
          example: https://api.aweber.com#serviceunavailable
          type: string
        message:
          description: A human friendly description of the error
          example: Failed to communicate with endpoint
          type: string
        status:
          description: The HTTP status code
          enum:
          - 503
          type: integer
        type:
          description: The API error type
          enum:
          - ServiceUnavailableError
          type: string
      type: object
    _accounts__accountId__lists__listId__landing_pages_get_503_response:
      example:
        error:
          documentation_url: https://api.aweber.com#serviceunavailable
          message: Failed to communicate with endpoint
          type: ServiceUnavailableError
          status: 7
      properties:
        error:
          $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages_get_503_response_error'
      type: object
    _accounts__accountId__lists__listId__landing_pages__landingPageId__get_400_response_error:
      description: |
        An error object.
        One of the following errors may be received:

        | Error Type                           | Explanation                              |
        |--------------------------------------|------------------------------------------|
        | BadRequestError                      | There was an error decoding query parameters |
        | MissingOAuthParametersError          | An OAuth parameter is missing in the request |
        | UnsupportedOAuthSignatureMethodError | The provided OAuth 1 signature method is unsupported. Only HMAC-SHA1 is supported. |
        | UnsupportedOAuthVersionError         | The provided OAuth 1 version is unsupported. |

        Please see the message body for more details.
      example:
        documentation_url: https://api.aweber.com#badrequest
        message: "Missing oauth parameters: oauth_consumer_key"
        type: MissingOAuthParametersError
        status: 0
      properties:
        documentation_url:
          description: A link to the documentation that describes the error
          example: https://api.aweber.com#badrequest
          type: string
        message:
          description: A human friendly description of the error
          example: "Missing oauth parameters: oauth_consumer_key"
          type: string
        status:
          description: The HTTP status code
          enum:
          - 400
          type: integer
        type:
          description: The API error type
          enum:
          - MissingOAuthParametersError
          type: string
      type: object
    _accounts__accountId__lists__listId__landing_pages__landingPageId__get_400_response:
      example:
        error:
          documentation_url: https://api.aweber.com#badrequest
          message: "Missing oauth parameters: oauth_consumer_key"
          type: MissingOAuthParametersError
          status: 0
      properties:
        error:
          $ref: '#/components/schemas/_accounts__accountId__lists__listId__landing_pages__landingPageId__get_400_response_error'
      type: object
    Endpoint_Error_error:
      description: |
        An error object.
        The following error may be received:

        | Error Type           | Explanation                              |
        |----------------------|------------------------------------------|
        | UnauthorizedError    | There is a problem with your authorization credentials |

        Please see the message body for more details.
      example:
        documentation_url: https://api.aweber.com#unauthorized
        message: Consumer key is invalid.
        type: UnauthorizedError
        status: 6
      properties:
        documentation_url:
          description: A link to the documentation that describes the error
          example: https://api.aweber.com#unauthorized
          type: string
        message:
          description: A human friendly description of the error
          example: Consumer key is invalid.
          type: string
        status:
          description: The HTTP status code
          enum:
          - 401
          type: integer
        type:
          description: The API error type
          enum:
          - UnauthorizedError
          type: string
      type: object
